
package com.globinch.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebService", targetNamespace = "http://service.globinch.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadImage", targetNamespace = "http://service.globinch.com/", className = "com.globinch.service.UploadImage")
    @ResponseWrapper(localName = "uploadImageResponse", targetNamespace = "http://service.globinch.com/", className = "com.globinch.service.UploadImageResponse")
    @Action(input = "http://service.globinch.com/MyWebService/uploadImageRequest", output = "http://service.globinch.com/MyWebService/uploadImageResponse")
    public String uploadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greetCustomer", targetNamespace = "http://service.globinch.com/", className = "com.globinch.service.GreetCustomer")
    @ResponseWrapper(localName = "greetCustomerResponse", targetNamespace = "http://service.globinch.com/", className = "com.globinch.service.GreetCustomerResponse")
    @Action(input = "http://service.globinch.com/MyWebService/greetCustomerRequest", output = "http://service.globinch.com/MyWebService/greetCustomerResponse")
    public String greetCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveImage", targetNamespace = "http://service.globinch.com/", className = "com.globinch.service.RetrieveImage")
    @ResponseWrapper(localName = "retrieveImageResponse", targetNamespace = "http://service.globinch.com/", className = "com.globinch.service.RetrieveImageResponse")
    @Action(input = "http://service.globinch.com/MyWebService/retrieveImageRequest", output = "http://service.globinch.com/MyWebService/retrieveImageResponse")
    public byte[] retrieveImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
